### ISSUE TITLE
Boolean value for whether certification was successful

### ISSUE THREAD

**Issue by mschifferstein** [elianderlohr/SemencesCertifiees#5]
A farmer should know immediately whether their application was successful. For this we need a hardcoded threshold value that marks certifications as successful based on the seed purity.

For the web interface, the user should see clearly in the overview which applications were successful and which were not.

**Comment by elianderlohr** [comment]
Done. Stored as "accepted". 0 = rejected and 1 = accepted. Simple check if purity above 98% it is accepted. Value gets returned for all endpoints and is implemented in the website!

**Comment by elianderlohr** [comment]
![image](https://github.com/elianderlohr/SemencesCertifiees/assets/26120768/8fc6af17-4038-47b9-9543-d7c821db3f81)
